PROMPT DROP TABLES;

DROP TABLE BOOKS CASCADE CONSTRAINTS;
DROP TABLE STUDENTS CASCADE CONSTRAINTS;
DROP TABLE BORROW CASCADE CONSTRAINTS;
DROP TABLE RESERVE CASCADE CONSTRAINTS;
DROP TABLE RENEW CASCADE CONSTRAINTS;

DROP TRIGGER BORROW_INSERT;
DROP TRIGGER BORROW_Delete;

COMMIT;